### ISSUE TITLE
Error while creating the cloud function (agent-template-banking)

### ISSUE THREAD

**Issue by TanishB** [GoogleCloudPlatform/dialogflow-virtual-agents-financial-services#1]
I uploaded the dialogflow-fulfillment zip file and chose runtime as Node.js 8 but getting this error `Deployment failure:
Function failed on loading user code. Error message: File index.js or function.js that is expected to define function doesn't exist in the root directory.` @swilliams11 
Please Help.

**Comment by swilliams11** [comment]
Hi @TanishB I will look into this error today.

**Comment by swilliams11** [comment]
@TanishB The issue is with the zip file.  This zip file has a folder with index.js and package.json in the folder.  The zip file should only include the index.js and package.json instead (no folder).  I will push the updated zip file in a few minutes.
